config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = {
  :address              => "smtp.gmail.com",
  :port                 => 587,
  :domain               => 'baci.lindsaar.net',
  :user_name            => 'jfigueir33@gmail.com',
  :password             => 'Jfig333!',
  :authentication       => 'Jfig333!',
  :enable_starttls_auto => true  }